language: python

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

branches:
    except:
        - gh-pages

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libfftw3-dev
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy cython setuptools
  - source active test-environment
  - python setup.py build_ext --inplace

script: python setup.py test
