language: python

python:
  - 2.7
  - 3.2
  - 3.3

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfftw3-dev cython python-numpy python-scipy python3-numpy python3-scipy
 - cython pyfftw/pyfftw.pyx
 - cython pyfftw/utils.pxi

install: pip install requirements.txt

script: python setup.py test
